# dbt_project.yml
name: 'crypto_analytics'
version: '1.0.0'
config-version: 2

profile: 'crypto_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_analytics:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: table
    
    marts:
      +materialized: table

vars:
  # Mathematical parameters
  volatility_window: 30
  ma_short_period: 7
  ma_long_period: 30
  rsi_period: 14
  bollinger_std_dev: 2
  var_confidence_level: 0.95

# Seeds configuration for reference data
seeds:
  crypto_analytics:
    crypto_metadata:
      +column_types:
        symbol: varchar(10)
        name: varchar(100)
        category: varchar(50)
        launch_date: date
