crypto_analytics:
  outputs:
    dev:
      type: sqlite
      database: '../crypto_warehouse.db'
      schema: 'main'
      schemas_and_paths:
        main: 'main'
      schema_directory: 'schemas'
  target: dev
