version: 2

sources:
  - name: raw_crypto
    description: "Raw cryptocurrency data from CoinGecko API"
    tables:
      - name: raw_crypto_prices
        description: "Raw daily cryptocurrency prices and volumes"
        columns:
          - name: id
            description: "Primary key"
            tests:
              - not_null
              - unique
          - name: symbol
            description: "Cryptocurrency symbol (BTC, ETH, ADA, etc.)"
            tests:
              - not_null
          - name: timestamp
            description: "Price timestamp"
            tests:
              - not_null
          - name: price
            description: "Price in USD"
            tests:
              - not_null
          - name: volume
            description: "24-hour trading volume"
            tests:
              - not_null
          - name: market_cap
            description: "Market capitalization"
          - name: extracted_at
            description: "Timestamp when data was extracted from API"
            tests:
              - not_null
